server:
  port: 9527

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.109.137.128:8848
        namespace: dev
    gateway:
      routes:
        - id: user-server
          uri: lb://user-server
          predicates:
            - Path=/user/**
        - id: order-server
          uri: lb://order-server
          predicates:
            - Path=/order/**
        - id: finance-server
          uri: lb://finance-server
          predicates:
            - Path=/finance/**
        - id: base-server
          uri: lb://base-server
          predicates:
            - Path=/base/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true